a-synchronous/rubico

- index.js
- test.js
from https://github.com/a-synchronous/rubico/issues/4
inspired from redux reducers
> transform works with objects

- index.js
from this [question](https://stackoverflow.com/questions/62112863/what-are-the-performance-implications-if-any-of-chaining-too-many-thens-on)
resolves this [issue](https://github.com/a-synchronous/rubico/issues/16)
> If you compare a .reduce() loop where you chain lots of .then() onto each other in order to sequence asynchronous operation and compare that to an await loop inside an async function where you finish one operation before starting the next, the main difference will be in peak memory usage.
> reduce; use await over extending promise chain

- index.js
- test.js
> flatMapArray

- .github/workflows/nodejs.yml
> new workflow with lint

- index.js
- test.js
Please base your branches off of `flat-map`
> flatMap base

- index.js
- test.js
resolves https://github.com/a-synchronous/rubico/issues/60 and https://github.com/a-synchronous/rubico/issues/61
> reduce(f, init); init can be a function

- index.js
- test.js
resolves https://github.com/a-synchronous/rubico/issues/57
> get defaultValue can be a function, optionalThunk

- x/README.md
- x/forEach.js
- x/forEach.test.js
resolves https://github.com/a-synchronous/rubico/issues/68
> forEach impl + test + doc

- x/README.md
- x/pluck.js
- x/pluck.test.js
resolves https://github.com/a-synchronous/rubico/issues/69
> pluck impl + test + doc

- .eslintrc.js
- x/README.md
- x/isObject.js
- x/isObject.test.js
- x/isString.js
- x/isString.test.js
resolves https://github.com/a-synchronous/rubico/issues/71 and https://github.com/a-synchronous/rubico/issues/70
> isObject, isString impl + doc + test

- x/README.md
- x/isEqual.js
- x/isEqual.test.js
resolves https://github.com/a-synchronous/rubico/issues/72
> isEqual impl + doc + test

- x/README.md
- x/isDeepEqual.js
- x/isDeepEqual.test.js
resolves https://github.com/a-synchronous/rubico/issues/73
> isDeepEqual impl + test + doc

- x/README.md
- x/unionWith.js
- x/unionWith.test.js
resolves https://github.com/a-synchronous/rubico/issues/74
> unionWith impl + test + doc

- x/README.md
- x/find.js
- x/find.test.js
resolves https://github.com/a-synchronous/rubico/issues/75
> find impl + doc + test

- x/README.md
- x/isEmpty.js
- x/isEmpty.test.js
resolves https://github.com/a-synchronous/rubico/issues/88
> isEmpty impl + doc + test

- x/README.md
- x/first.js
- x/first.test.js
- x/last.js
- x/last.test.js
resolves https://github.com/a-synchronous/rubico/issues/89 and https://github.com/a-synchronous/rubico/issues/56
> rubico/x/first and rubico/x/last

- benchmarks/switchCase.js
resolves https://github.com/a-synchronous/rubico/issues/106
> switchCase benchmarks

- benchmarks/tryCatchTimeInLoop.js
resolves https://github.com/a-synchronous/rubico/issues/120
> tryCatch timeInLoop benchmarks

- x/defaultsDeep.js
- x/defaultsDeep.test.js
resolves https://github.com/a-synchronous/rubico/issues/124
> defaultsDeep handle type errors

- monad/possible-promise.benchmark.js
- monad/possible-promise.js
- monad/possible-promise.test.js
- package.json
resolves https://github.com/a-synchronous/rubico/issues/127
> PossiblePromise monad

- CHANGELOG.md
- package.json
- x/find.benchmark.js
- x/find.js
- x/find.test.js
Revamps find to use PossiblePromise
> find revamp

- _internal/hasOwn.js
- _internal/isObject.js
- _internal/objectMapOwn.js
- benchmarks/misc.js
- map.js
- test.js
Closes #143 
This is my first contribution to this repo so by all means, let me know if there are any changes you need or if I've missed the mark. I tried to model it after existing methods as much as possible while matching the test case provided above. The tests could likely be expanded. Let me know if you'd like me to tackle that.
This is a super interesting library that I'll be using on my next personal project! Thanks for calling it out on Twitter to me.
> Add map.own

- benchmarks/misc.js
- pipe.js
- test.js
completes https://github.com/a-synchronous/rubico/issues/216
> eager pipe

- x/uniq.benchmark.js
- x/uniq.js
Hello,
thank you for this fantastic library.
I would like to suggest this small change in implementation.
Best regards,
Jarda
> better uniq implementation

- set.js
- test.js
> property value passed to set may be a resolver

- Transducer.js
- all.js
- always.js
- and.js
- any.js
- assign.js
- curry.js
- filter.js
- flatMap.js
- fork.js
- get.js
- map.js
- not.js
- omit.js
- or.js
- pick.js
- pipe.js
- reduce.js
- set.js
- switchCase.js
- tap.js
- thunkify.js
- transform.js
- tryCatch.js
Revised documentation for the following functions:
* pipe
* tap
* switchCase
* tryCatch
* fork
* assign
* get
* set
* pick
* omit
* map
* filter
* reduce
* transform
* flatMap
* and
* or
* not
* any
* all
* eq
* gt
* lt
* gte
* lte
* thunkify
* always
* curry
* __
> Revised documentation for rubico core functions

- switchCase.js
Adds ternary API to swtichCase docs
> switchCase docs addition

- fork.js
- pipe.js
- switchCase.js
- tap.js
- tryCatch.js
Rewords some of the descriptions of the core functions
> Docs touchups

- assign.js
- fork.js
- switchCase.js
covers switchCase, fork, and assign
> More revisions

- README.md
It looks more natural to me lowercase
> docs lowercase rubico

- README.md
main example reflects one intended use of pipe
> update main example to use eager API

- README.md
- rubico.js
example reflects intended usage, categories are listed to aid understanding
> Rework example and recategorize methods

- README.md
also removes the unnecesary count of operators
> use versatile to describe rubico

- README.md
More examples to illustrate rubico
> more examples in readme

- README.md
More documentation on transducers and their use with compose
> note about compose

- build
- dist-test.js
Dist missing these bundles before
> Distribute Transducer.js and rubico global and compose

- README.md
> have people import minified files by default

- README.md
Reword so intro can sound more natural
> reword some lines in the readme

- CONTRIBUTING.md
- README.md
Adds steps to release a new version of the library
> add steps to release

- tap.js
- test.js
resolves https://github.com/a-synchronous/rubico/issues/257
> eager API for tap

- README.md
helps it look nicer especially on the website
> Take out <br> in readme

- README.md
change some wording in the docs
> compose objects -> handle objects

- eq.js
- every.js
- filter.js
- flatMap.js
- get.js
- gt.js
- gte.js
- lt.js
- lte.js
- map.js
- reduce.js
- set.js
- some.js
- switchCase.js
- transform.js
Covers API more completely and fixes examples in several places
> prepare core docs for v2

- Transducer.js
Documents the Transducer module for rubico.land
> Transducer docs

- README.md
Let's consolidate the chat to this issue: https://github.com/a-synchronous/rubico/issues/29
> remove gitter

- _internal/arrayMapSeries.js
- test.js
> map.series index
